import { useEffect, useState } from "react";

export default function ILAWPreview({ lessonPlan, onBack }) {
  const [plan, setPlan] = useState(() => structuredClone(lessonPlan));
  const [saved, setSaved] = useState(false);

  const [modifyPrompt, setModifyPrompt] = useState("");
  const [isModifying, setIsModifying] = useState(false);

  const API_URL = import.meta.env.VITE_API_URL;

  const handleSaveAll = () => {
    try {
      localStorage.setItem("makai-ilaw-draft", JSON.stringify(plan));

      setSaved(true);

      window.setTimeout(() => {
        setSaved(false);
      }, 2000);
    } catch (error) {
      console.error("Failed to save ILAW draft:", error);
    }
  };

  const handleExportDocx = async () => {
    try {
      const response = await fetch(`${API_URL}/api/ilaw/export-docx`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(plan),
      });

      if (!response.ok) {
        throw new Error("Failed to generate DOCX");
      }

      const blob = await response.blob();

      const url = window.URL.createObjectURL(blob);

      const link = document.createElement("a");

      link.href = url;
      link.download = "ILAW_Lesson_Plan.docx";

      document.body.appendChild(link);

      link.click();

      link.remove();

      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("DOCX export failed:", error);
      alert("Failed to export ILAW lesson plan.");
    }
  };

  const handleModifyPlan = async () => {
    const prompt = modifyPrompt.trim();

    if (!prompt) {
      return;
    }

    try {
      setIsModifying(true);

      const response = await fetch(`${API_URL}/api/ilaw/modify`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          instruction: prompt,
          lesson_plan: plan,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.detail || "Failed to modify ILAW lesson plan");
      }

      console.log("Modified ILAW plan:", data);

      // Backend should return the updated lesson plan
      const updatedPlan = data.lesson_plan || data;

      setPlan(structuredClone(updatedPlan));

      setModifyPrompt("");
      setSaved(false);
    } catch (error) {
      console.error("ILAW modification failed:", error);

      alert(error.message || "Failed to modify the lesson plan.");
    } finally {
      setIsModifying(false);
    }
  };

  useEffect(() => {
    setPlan(structuredClone(lessonPlan));
  }, [lessonPlan]);

  const updatePlan = (updater) => {
    setPlan((current) => {
      const next = structuredClone(current);
      updater(next);
      return next;
    });
    setSaved(false);
  };

  const saveSession = (index, nextSession) => {
    updatePlan((next) => {
      next.sessions[index] = nextSession;
    });
  };

  return (
    <div className="min-h-screen bg-[#0b0f19] text-white">
      <header className="sticky top-0 z-20 border-b border-white/10 bg-[#0b0f19]/95 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <button
            onClick={onBack}
            className="text-sm text-gray-400 hover:text-white"
          >
            ← Back to IMAC-AI
          </button>
          <div className="flex items-center gap-2">
            {saved && <span className="text-xs text-green-400">✓ Saved</span>}

            <button
              onClick={handleSaveAll}
              className="rounded-lg border border-white/10 px-4 py-2 text-sm text-gray-300 hover:bg-white/5"
            >
              --
            </button>

            <button
              type="button"
              onClick={handleExportDocx}
              className="rounded-lg bg-gradient-to-r from-[#5B4CFF] via-[#7C3AED] to-[#A855F7] px-5 py-2.5 text-sm font-medium text-white hover:bg-green-700"
            >
              Export DOCX
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-6 py-8">
        <div className="mb-8">
          <p className="text-xs font-medium uppercase tracking-wider text-white">
            Generated by IMAC-Ai
          </p>
          <h1 className="mt-2 text-2xl font-semibold">ILAW Lesson Plan</h1>
          <p className="mt-1 text-sm text-gray-500">
            Review and edit your generated lesson plan.
          </p>
        </div>

        <div className="space-y-5">
          <ILAWSection
            title="LESSON INFORMATION"
            editableValue={[
              `Lesson Title: ${plan.lesson_information.title}`,
              `Learning Area: ${plan.lesson_information.learning_area}`,
              `Teacher/s: ${plan.lesson_information.teachers.join(", ")}`,
              `Grade Level: ${plan.lesson_information.grade_level}`,
              `Section: ${plan.lesson_information.section || "Not specified"}`,
              `Number of Sessions: ${plan.lesson_information.sessions}`,
            ].join("\n")}
            onSave={(value) =>
              updatePlan((next) => {
                const fields = parseKeyValueText(value);
                if (fields["Lesson Title"] !== undefined)
                  next.lesson_information.title = fields["Lesson Title"];
                if (fields["Learning Area"] !== undefined)
                  next.lesson_information.learning_area =
                    fields["Learning Area"];
                if (fields["Teacher/s"] !== undefined)
                  next.lesson_information.teachers = fields["Teacher/s"]
                    .split(",")
                    .map((x) => x.trim())
                    .filter(Boolean);
                if (fields["Grade Level"] !== undefined)
                  next.lesson_information.grade_level = fields["Grade Level"];
                if (fields["Section"] !== undefined)
                  next.lesson_information.section =
                    fields["Section"] === "Not specified"
                      ? ""
                      : fields["Section"];
                if (
                  fields["Number of Sessions"] !== undefined &&
                  Number.isFinite(Number(fields["Number of Sessions"]))
                )
                  next.lesson_information.sessions = Number(
                    fields["Number of Sessions"],
                  );
              })
            }
          >
            <InfoRow
              label="Lesson Title"
              value={plan.lesson_information.title}
            />
            <InfoRow
              label="Learning Area"
              value={plan.lesson_information.learning_area}
            />
            <InfoRow
              label="Teacher/s"
              value={plan.lesson_information.teachers.join(", ")}
            />
            <InfoRow
              label="Grade Level"
              value={plan.lesson_information.grade_level}
            />
            <InfoRow
              label="Section"
              value={plan.lesson_information.section || "Not specified"}
            />
            <InfoRow
              label="Number of Sessions"
              value={plan.lesson_information.sessions}
            />
          </ILAWSection>

          <ILAWSection
            title="REFERENCES"
            editableValue={plan.references.join("\n")}
            onSave={(value) =>
              updatePlan((next) => {
                next.references = textToList(value);
              })
            }
          >
            <ListBlock title="References" items={plan.references} />
          </ILAWSection>

          <ILAWSection
            title="DECLARATION OF AI USE"
            editableValue={plan.declaration_of_ai_use}
            onSave={(value) =>
              updatePlan((next) => {
                next.declaration_of_ai_use = value;
              })
            }
          >
            <ContentBlock
              title="Declaration"
              content={plan.declaration_of_ai_use}
            />
          </ILAWSection>

          <ILAWSection
            title="I – INTENTIONS"
            editableValue={[
              `Content Standard: ${plan.intentions.content_standard}`,
              `Performance Standard: ${plan.intentions.performance_standard}`,
              "Learning Competencies:",
              ...plan.intentions.learning_competencies.map((x) => `- ${x}`),
              "Specific Objectives:",
              ...plan.intentions.specific_objectives.map((x) => `- ${x}`),
              `Learning Objectives: ${plan.intentions.learning_objectives}`,
              `Learner Context: ${plan.intentions.learner_context}`,
            ].join("\n")}
            onSave={(value) =>
              updatePlan((next) => {
                const sections = parseLabeledSections(value);
                if (sections["Content Standard"] !== undefined)
                  next.intentions.content_standard =
                    sections["Content Standard"];
                if (sections["Performance Standard"] !== undefined)
                  next.intentions.performance_standard =
                    sections["Performance Standard"];
                if (sections["Learning Competencies"] !== undefined)
                  next.intentions.learning_competencies = textToList(
                    sections["Learning Competencies"],
                  );
                if (sections["Specific Objectives"] !== undefined)
                  next.intentions.specific_objectives = textToList(
                    sections["Specific Objectives"],
                  );
                if (sections["Learning Objectives"] !== undefined)
                  next.intentions.learning_objectives =
                    sections["Learning Objectives"];
                if (sections["Learner Context"] !== undefined)
                  next.intentions.learner_context = sections["Learner Context"];
              })
            }
          >
            <ContentBlock
              title="Content Standard"
              content={plan.intentions.content_standard}
            />
            <ContentBlock
              title="Performance Standard"
              content={plan.intentions.performance_standard}
            />
            <ListBlock
              title="Learning Competencies"
              items={plan.intentions.learning_competencies}
            />
            <ListBlock
              title="Specific Objectives"
              items={plan.intentions.specific_objectives}
            />
            <ContentBlock
              title="Learning Objectives"
              content={plan.intentions.learning_objectives}
            />
            <ContentBlock
              title="Learner Context"
              content={plan.intentions.learner_context}
            />
          </ILAWSection>

          <ILAWSection
            title="L - LEARNING EXPERIENCES"
            editableValue={[
              `Learning Resources: ${plan.learning_experiences.learning_resources}`,
              `Pre-Lesson: ${plan.learning_experiences.pre_lesson}`,
              `Flow / Daylong: ${plan.learning_experiences.flow_daylong.activity}`,
              `Discussion: ${plan.learning_experiences.flow_daylong.discussion}`,
              `Deduction / Generalization: ${plan.learning_experiences.flow_daylong.deduction}`,
              "Concepts:",
              ...plan.learning_experiences.flow_daylong.concepts.map(
                (x) => `- ${x}`,
              ),
              `Opportunities for Integration: ${plan.learning_experiences.opportunities_for_integration}`,
            ].join("\n")}
            onSave={(value) =>
              updatePlan((next) => {
                const sections = parseLabeledSections(value);
                if (sections["Learning Resources"] !== undefined)
                  next.learning_experiences.learning_resources =
                    sections["Learning Resources"];
                if (sections["Pre-Lesson"] !== undefined)
                  next.learning_experiences.pre_lesson = sections["Pre-Lesson"];
                if (sections["Flow / Daylong"] !== undefined)
                  next.learning_experiences.flow_daylong.activity =
                    sections["Flow / Daylong"];
                if (sections["Discussion"] !== undefined)
                  next.learning_experiences.flow_daylong.discussion =
                    sections["Discussion"];
                if (sections["Deduction / Generalization"] !== undefined)
                  next.learning_experiences.flow_daylong.deduction =
                    sections["Deduction / Generalization"];
                if (sections["Concepts"] !== undefined)
                  next.learning_experiences.flow_daylong.concepts = textToList(
                    sections["Concepts"],
                  );
                if (sections["Opportunities for Integration"] !== undefined)
                  next.learning_experiences.opportunities_for_integration =
                    sections["Opportunities for Integration"];
              })
            }
          >
            <ContentBlock
              title="Learning Resources"
              content={plan.learning_experiences.learning_resources}
            />
            <ContentBlock
              title="Pre-Lesson"
              content={plan.learning_experiences.pre_lesson}
            />
            <ContentBlock
              title="Flow / Daylong"
              content={plan.learning_experiences.flow_daylong.activity}
            />
            <ContentBlock
              title="Discussion"
              content={plan.learning_experiences.flow_daylong.discussion}
            />
            <ContentBlock
              title="Deduction / Generalization"
              content={plan.learning_experiences.flow_daylong.deduction}
            />
            <ListBlock
              title="Concepts"
              items={plan.learning_experiences.flow_daylong.concepts}
            />
            <ContentBlock
              title="Opportunities for Integration"
              content={plan.learning_experiences.opportunities_for_integration}
            />

            <div className="mt-6 border-t border-white/10 pt-5">
              <h3 className="mb-4 text-base font-medium text-white">
                Sessions
              </h3>
              <div className="space-y-4">
                {plan.sessions.map((session, index) => (
                  <EditableSession
                    key={session.session_number ?? index}
                    session={session}
                    onSave={(nextSession) => saveSession(index, nextSession)}
                  />
                ))}
              </div>
            </div>
          </ILAWSection>

          <ILAWSection
            title="A - ASSESSMENT"
            editableValue={[
              `Formative Assessment: ${plan.assessment.formative_assessment}`,
              "Guide Questions:",
              ...plan.assessment.guide_questions.map((x) => `- ${x}`),
            ].join("\n")}
            onSave={(value) =>
              updatePlan((next) => {
                const sections = parseLabeledSections(value);
                if (sections["Formative Assessment"] !== undefined)
                  next.assessment.formative_assessment =
                    sections["Formative Assessment"];
                if (sections["Guide Questions"] !== undefined)
                  next.assessment.guide_questions = textToList(
                    sections["Guide Questions"],
                  );
              })
            }
          >
            <ContentBlock
              title="Formative Assessment"
              content={plan.assessment.formative_assessment}
            />
            <ListBlock
              title="Guide Questions"
              items={plan.assessment.guide_questions}
            />
          </ILAWSection>

          <ILAWSection
            title="W - WAYS FORWARD"
            editableValue={[
              `Extended Learning Opportunities: ${plan.ways_forward.extended_learning}`,
              `Reflections: ${plan.ways_forward.reflections}`,
              `Application: ${plan.ways_forward.application}`,
            ].join("\n")}
            onSave={(value) =>
              updatePlan((next) => {
                const sections = parseLabeledSections(value);
                if (sections["Extended Learning Opportunities"] !== undefined)
                  next.ways_forward.extended_learning =
                    sections["Extended Learning Opportunities"];
                if (sections["Reflections"] !== undefined)
                  next.ways_forward.reflections = sections["Reflections"];
                if (sections["Application"] !== undefined)
                  next.ways_forward.application = sections["Application"];
              })
            }
          >
            <ContentBlock
              title="Extended Learning Opportunities"
              content={plan.ways_forward.extended_learning}
            />
            <ContentBlock
              title="Reflections"
              content={plan.ways_forward.reflections}
            />
            <ContentBlock
              title="Application"
              content={plan.ways_forward.application}
            />
          </ILAWSection>

          <ILAWSection
            title="PREPARED, CHECKED AND NOTED"
            editableValue={[
              `Prepared by: ${plan.prepared_checked_noted.prepared_by}`,
              `Checked by: ${plan.prepared_checked_noted.checked_by}`,
              `Noted by: ${plan.prepared_checked_noted.noted_by}`,
            ].join("\n")}
            onSave={(value) =>
              updatePlan((next) => {
                const fields = parseKeyValueText(value);
                if (fields["Prepared by"] !== undefined)
                  next.prepared_checked_noted.prepared_by =
                    fields["Prepared by"];
                if (fields["Checked by"] !== undefined)
                  next.prepared_checked_noted.checked_by = fields["Checked by"];
                if (fields["Noted by"] !== undefined)
                  next.prepared_checked_noted.noted_by = fields["Noted by"];
              })
            }
          >
            <div className="grid gap-6 md:grid-cols-3">
              <SignatureBlock
                label="Prepared by"
                value={plan.prepared_checked_noted.prepared_by}
                role="Teacher"
              />
              <SignatureBlock
                label="Checked by"
                value={plan.prepared_checked_noted.checked_by}
                role="Master Teacher / Head Teacher"
              />
              <SignatureBlock
                label="Noted by"
                value={plan.prepared_checked_noted.noted_by}
                role="School Principal"
              />
            </div>
          </ILAWSection>
        </div>

        <div className="mt-8 rounded-2xl border border-white/10 bg-[#111722] p-4">
          <div className="flex items-center gap-3">
            <input
              type="text"
              value={modifyPrompt}
              onChange={(e) => setModifyPrompt(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleModifyPlan();
                }
              }}
              disabled={isModifying}
              placeholder="Ask IMAC-AI to modify this lesson plan..."
              className="flex-1 bg-transparent text-sm text-gray-200 outline-none placeholder:text-gray-600 disabled:opacity-50"
            />

            <button
              type="button"
              onClick={handleModifyPlan}
              disabled={!modifyPrompt.trim() || isModifying}
              className="rounded-lg bg-gradient-to-r from-[#5B4CFF] via-[#7C3AED] to-[#A855F7] px-4 py-2 text-sm text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {isModifying ? "..." : "↑"}
            </button>
          </div>

          {isModifying && (
            <p className="mt-2 text-xs text-gray-500">
              IMAC-AI is updating your lesson plan...
            </p>
          )}
        </div>
      </main>
    </div>
  );
}

function ILAWSection({ title, children, editableValue, onSave }) {
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState(editableValue ?? "");

  useEffect(() => {
    if (!isEditing) setEditValue(editableValue ?? "");
  }, [editableValue, isEditing]);

  const handleSave = () => {
    onSave?.(editValue);
    setIsEditing(false);
  };

  return (
    <section className="rounded-2xl border border-white/10 bg-[#111722]">
      <div className="flex items-center justify-between border-b border-white/10 px-5 py-4">
        <h2 className="font-medium">{title}</h2>
        {onSave && !isEditing && (
          <button
            onClick={() => {
              setEditValue(editableValue ?? "");
              setIsEditing(true);
            }}
            className="rounded-lg px-3 py-1.5 text-xs text-gray-400 hover:bg-white/5 hover:text-white"
          >
            Edit
          </button>
        )}
      </div>

      <div className="p-5">
        {isEditing ? (
          <div>
            <textarea
              value={editValue}
              onChange={(e) => setEditValue(e.target.value)}
              rows={10}
              autoFocus
              className="w-full resize-y rounded-xl border border-green-500/30 bg-[#0b0f19] p-4 text-sm leading-6 text-gray-200 outline-none focus:border-green-500/60"
            />
            <div className="mt-4 flex justify-end gap-2">
              <button
                onClick={() => {
                  setEditValue(editableValue ?? "");
                  setIsEditing(false);
                }}
                className="rounded-lg border border-white/10 px-4 py-2 text-sm text-gray-400 hover:bg-white/5 hover:text-white"
              >
                Cancel
              </button>
              <button
                onClick={handleSave}
                className="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-500"
              >
                Save
              </button>
            </div>
          </div>
        ) : (
          children
        )}
      </div>
    </section>
  );
}

function EditableSession({ session, onSave }) {
  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState(session);

  useEffect(() => {
    if (!isEditing) setDraft(session);
  }, [session, isEditing]);

  return (
    <div className="rounded-xl border border-white/10 bg-[#0b0f19] p-4">
      <div className="mb-4 flex items-center justify-between">
        <h3 className="text-base font-medium text-white">
          Session {session.session_number}
        </h3>
        {!isEditing && (
          <button
            onClick={() => {
              setDraft(session);
              setIsEditing(true);
            }}
            className="rounded-lg px-3 py-1.5 text-xs text-gray-400 hover:bg-white/5 hover:text-white"
          >
            Edit
          </button>
        )}
      </div>

      {isEditing ? (
        <div className="space-y-4">
          <EditorField
            label="Topic"
            value={draft.topic}
            onChange={(value) => setDraft({ ...draft, topic: value })}
          />
          <EditorField
            label="Learning Activities"
            value={draft.activities}
            rows={6}
            onChange={(value) => setDraft({ ...draft, activities: value })}
          />
          <EditorField
            label="Assessment"
            value={draft.assessment}
            rows={5}
            onChange={(value) => setDraft({ ...draft, assessment: value })}
          />
          <div className="flex justify-end gap-2">
            <button
              onClick={() => {
                setDraft(session);
                setIsEditing(false);
              }}
              className="rounded-lg border border-white/10 px-4 py-2 text-sm text-gray-400 hover:bg-white/5 hover:text-white"
            >
              Cancel
            </button>
            <button
              onClick={() => {
                onSave(draft);
                setIsEditing(false);
              }}
              className="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-500"
            >
              Save
            </button>
          </div>
        </div>
      ) : (
        <>
          <ContentBlock title="Topic" content={session.topic} />
          <ContentBlock
            title="Learning Activities"
            content={session.activities}
          />
          <ContentBlock title="Assessment" content={session.assessment} />
        </>
      )}
    </div>
  );
}

function EditorField({ label, value, onChange, rows = 4 }) {
  return (
    <div>
      <label className="mb-2 block text-sm font-medium text-gray-200">
        {label}
      </label>
      <textarea
        value={value ?? ""}
        onChange={(e) => onChange(e.target.value)}
        rows={rows}
        className="w-full resize-y rounded-xl border border-white/10 bg-[#111722] p-3 text-sm leading-6 text-gray-200 outline-none focus:border-green-500/50"
      />
    </div>
  );
}

function SignatureBlock({ label, value, role }) {
  return (
    <div>
      <p className="text-xs font-medium uppercase tracking-wide text-gray-500">
        {label}
      </p>
      <p className="mt-2 text-sm text-gray-200">{value}</p>
      <p className="mt-1 text-xs text-gray-500">{role}</p>
    </div>
  );
}

function InfoRow({ label, value }) {
  return (
    <div className="grid gap-1 border-b border-white/5 py-3 last:border-0 md:grid-cols-[200px_1fr]">
      <span className="text-sm text-gray-500">{label}</span>
      <span className="text-sm text-gray-200">{value}</span>
    </div>
  );
}

function ContentBlock({ title, content }) {
  return (
    <div className="mb-5 last:mb-0">
      <h4 className="text-sm font-medium text-gray-200">{title}</h4>
      <p className="mt-2 whitespace-pre-line text-sm leading-6 text-gray-400">
        {content}
      </p>
    </div>
  );
}

function ListBlock({ title, items }) {
  return (
    <div className="mb-5 last:mb-0">
      <h4 className="text-sm font-medium text-gray-200">{title}</h4>
      <ul className="mt-3 space-y-2">
        {(items ?? []).map((item, index) => (
          <li
            key={`${item}-${index}`}
            className="text-sm leading-6 text-gray-400"
          >
            • {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

function textToList(value) {
  return value
    .split("\n")
    .map((item) => item.replace(/^[-•]\s*/, "").trim())
    .filter(Boolean);
}

function parseKeyValueText(value) {
  const result = {};
  value.split("\n").forEach((line) => {
    const index = line.indexOf(":");
    if (index === -1) return;
    const key = line.slice(0, index).trim();
    const content = line.slice(index + 1).trim();
    if (key) result[key] = content;
  });
  return result;
}

function parseLabeledSections(value) {
  const labels = [
    "Content Standard",
    "Performance Standard",
    "Learning Competencies",
    "Specific Objectives",
    "Learning Objectives",
    "Learner Context",
    "Learning Resources",
    "Pre-Lesson",
    "Flow / Daylong",
    "Discussion",
    "Deduction / Generalization",
    "Concepts",
    "Opportunities for Integration",
    "Formative Assessment",
    "Guide Questions",
    "Extended Learning Opportunities",
    "Reflections",
    "Application",
  ];
  const lines = value.split("\n");
  const result = {};
  let current = null;
  let buffer = [];

  const flush = () => {
    if (current) result[current] = buffer.join("\n").trim();
  };

  lines.forEach((line) => {
    const label = labels.find((item) => line.trim().startsWith(`${item}:`));
    if (label) {
      flush();
      current = label;
      buffer = [
        line
          .trim()
          .slice(label.length + 1)
          .trim(),
      ].filter(Boolean);
    } else if (current) {
      buffer.push(line);
    }
  });

  flush();
  return result;
}
