from pathlib import Path
from pptx import Presentation


def create_test_presentation():
    # Create output folder if it doesn't exist
    output_dir = Path("generated")
    output_dir.mkdir(exist_ok=True)

    prs = Presentation()

    # -------------------------
    # Title Slide
    # -------------------------
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)

    slide.shapes.title.text = "Mak-AI PowerPoint Demo"
    slide.placeholders[1].text = "Generated using python-pptx"

    # -------------------------
    # Content Slide
    # -------------------------
    bullet_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_layout)

    slide.shapes.title.text = "Features"

    text_frame = slide.placeholders[1].text_frame

    features = [
        "AI-generated presentations",
        "PDF to PowerPoint",
        "Charts and tables",
        "Professional themes"
    ]

    for i, feature in enumerate(features):
        if i == 0:
            p = text_frame.paragraphs[0]
        else:
            p = text_frame.add_paragraph()

        p.text = feature
        p.level = 0

    output_file = output_dir / "presentation.pptx"
    prs.save(output_file)

    return output_file

def create_presentation(title, slides):
    # Create output folder if it doesn't exist
    output_dir = Path("generated")
    output_dir.mkdir(exist_ok=True)

    prs = Presentation()

    # -------------------------
    # Title Slide
    # -------------------------
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)

    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by Mak-AI"

    # -------------------------
    # Content Slides
    # -------------------------
    bullet_layout = prs.slide_layouts[1]

    for slide_data in slides:
        slide = prs.slides.add_slide(bullet_layout)

        slide.shapes.title.text = slide_data["title"]

        text_frame = slide.placeholders[1].text_frame
        text_frame.clear()

        for i, bullet in enumerate(slide_data["content"]):
            if i == 0:
                p = text_frame.paragraphs[0]
            else:
                p = text_frame.add_paragraph()

            p.text = bullet
            p.level = 0

    output_file = output_dir / "presentation.pptx"
    prs.save(output_file)

    return output_file