from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

from services.theme_manager import get_theme
from services.image_search import get_slide_image
from pptx.util import Pt


def add_background(slide, prs, theme):
    background = slide.shapes.add_picture(
        str(theme["background"]),
        0,
        0,
        width=prs.slide_width,
        height=prs.slide_height
    )

    slide.shapes._spTree.remove(background._element)
    slide.shapes._spTree.insert(2, background._element)


def add_logo(slide, theme):

    logo = theme["logo"]

    if logo.exists():
        slide.shapes.add_picture(
            str(logo),
            Inches(8.0),
            Inches(0.35),
            width=Inches(0.8)
        )


def add_title(slide, text, theme):

    textbox = slide.shapes.add_textbox(
        Inches(1.8),
        Inches(1.2),
        Inches(8.2),
        Inches(1.0)
    )

    tf = textbox.text_frame
    p = tf.paragraphs[0]
    p.text = text

    p.font.name = theme["title_font"]
    p.font.size = Pt(32)
    p.font.bold = True
    p.font.color.rgb = RGBColor(34, 34, 34)

    p.alignment = PP_ALIGN.LEFT

def add_subtitle(slide, text, theme):

    textbox = slide.shapes.add_textbox(
        Inches(1.8),      # align with title
        Inches(1.85),     # moved down
        Inches(8),
        Inches(0.4)
    )

    tf = textbox.text_frame
    p = tf.paragraphs[0]

    p.text = text
    p.font.name = theme["body_font"]
    p.font.size = Pt(16)
    p.font.color.rgb = theme["body_color"]


def add_bullets(slide, bullets, theme):

    textbox = slide.shapes.add_textbox(
        Inches(0.8),
        Inches(1.75),
        Inches(5.2),
        Inches(4.6)
    )

    tf = textbox.text_frame
    tf.word_wrap = True

    for i, bullet in enumerate(bullets):

        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()

        p.text = f"• {bullet}"      # <-- add bullet back
        p.level = 0
        p.space_after = Pt(8)

        p.font.name = theme["body_font"]
        p.font.size = Pt(18)
        p.font.color.rgb = theme["body_color"]


def create_test_presentation():

    slides = [
        {
            "title": "Features",
            "content": [
                "AI-generated presentations",
                "PDF to PowerPoint",
                "Professional themes",
                "Automatic formatting"
            ]
        },
        {
            "title": "Future Plans",
            "content": [
                "Charts",
                "AI Images",
                "Icons",
                "Animations"
            ]
        }
    ]

    return create_presentation(
        "Mak-AI PowerPoint Demo",
        slides
    )


def create_presentation(title, slides):

    theme = get_theme("business")

    output_dir = Path("generated")
    output_dir.mkdir(exist_ok=True)

    prs = Presentation()

    # ==================================================
    # TITLE SLIDE
    # ==================================================

    blank = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank)

    add_background(slide, prs, theme)
    add_logo(slide, theme)

    add_title(slide, title, theme)

    add_subtitle(
        slide,
        "Generated by Mak-AI",
        theme
    )

    # ==================================================
    # CONTENT SLIDES
    # ==================================================

    for slide_data in slides:
        
        slide = prs.slides.add_slide(blank)

        add_background(slide, prs, theme)
        add_logo(slide, theme)

        add_title(
            slide,
            slide_data["title"],
            theme
        )
        image = get_slide_image(slide_data["title"])
        if image.exists():

            slide.shapes.add_picture(
                str(image),
                Inches(6.4),
                Inches(1.5),
                width=Inches(2.7)
            )

        add_bullets(
            slide,
            slide_data["content"],
            theme
        )

    output = output_dir / "presentation.pptx"

    prs.save(output)

    return output